### ISSUE TITLE
Allow gh githubuser/githubrepo

### ISSUE THREAD

**Issue by hacfi** [jdxcode/gh#6]
Just discovered this nice plugin and I think it would be quite practical to allow `gh githubuser/githubrepo` so you can copy/paste from the url. We just need a small check if the argv contains a `/` and then split it.

**Comment by dickeyxxx** [comment]
it's not that simple, making it work with autocomplete would be tricky

**Comment by dickeyxxx** [comment]
looking at this again, I'm not sure why I said it'd be hard, it's totally doable to make it work with autocomplete

**Comment by jdxcode** [comment]
this is done (without completions), but I'm going back to my original thought. I have no idea how to make the completions work haha
